#PRACTICE TEST 2, 22 ABRIL 2023.
#USAC, MAESTRIA INGENIERIA PARA INDUSTRIA CON ESPECIALIDAD EN CIENCIA DE COMPUTACION.
#CATEDRATICO: MSC ING. EDWIN ESTUARDO ZAPETA GOMEZ.
#CLASE: FUNDAMENTOS DE PROGRAMACION Y SCRIPTING.
#ALUMNO: GERMAN CONTRERAS JACINTO.


```{r}
library(tidyverse)
library(nycflights13)
view(flights)
view(airports)
view(planes)
view(airlines)
view(weather)
flights
```
# 1. Inner-join
#1.1
```{r}
planes%>%
inner_join(flights, by="tailnum")
```
#1.2
```{r}
airlines%>%
  inner_join(flights,by="carrier")
```
#1.3
```{r}
airports%>%
  inner_join(flights,by=c("faa"="origin"))%>%
  inner_join(flights, by=c("faa"="dest"))
```
#1.4
```{r}
flights
weather
weather%>%
  inner_join(flights,by=c("year","month","day","hour","origin"))
```
#2. Data manipulation
#2.1
```{r}
flights%>%
  count(year,month,day)%>%
  filter(n>1000)%>%
  arrange(n)
```
#2.2
```{r}
flights_selected <- flights%>%
  select(hour,origin,dest,tailnum,carrier,arr_delay,dep_delay,year:day)
flights_selected
```
#2.3
```{r}
airlines%>%
  inner_join(flights_selected,by="carrier")%>%
  select(-origin,-dest)%>%
  mutate(tot_delay=arr_delay+dep_delay)
```
#2.4
```{r}
flights
weather
precip_delay<-flights%>%
  inner_join(weather,by=c("year","month","day","hour","origin"))%>%
  group_by(precip)%>%
  summarize(delay=mean(dep_delay,na.rm=TRUE))%>%
  replace_na(list(delay=0))

precip_delay
```
#2.5
```{r}
ggplot(precip_delay,aes(x=precip,y=delay))+geom_point()
```
#2.6
```{r}
flights
flights_airports <- flights%>%
  filter(year==2013,month==5,day==10)%>%
  group_by(dest)%>%
  summarize(delay=mean(arr_delay,na.rm=TRUE))%>%
  inner_join(airports,by=c("dest"="faa"))
flights_airports
```
#2.7
```{r}
ggplot(flights_airports, aes(x=lon,y=lat, colour=delay,size=delay))+geom_point()
```

#2.8
```{r}
flights%>%
  inner_join(planes,by="tailnum",suffix=c("_flights","_planes"))%>%
  transmute(tailnum,manufacturer,pi=(dep_delay+arr_delay)/air_time)
```
